# Generated by Django 4.0.5 on 2022-06-11 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.ImageField(default='https://www.thespruce.com/thmb/Cn3rYk2FGUYrM8f_Yk99y9vcu8Q=/2121x1414/filters:no_upscale():max_bytes(150000):strip_icc()/patterned-carpet-in-decorative-living-room-interior-with-painting-above-couch--real-photo-996692496-dec2473f5d434d2c8eb50a7cd18b3758.jpg', upload_to='images')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('bio', models.TextField(blank=True, default='awwards Bio', max_length=600)),
                ('contact', models.EmailField(blank=True, max_length=300)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
